config/routes.rb
Rails.application.routes.draw do

  get 'status_etudiants/index/:id', to: "status_etudiants#index", as: 'satusE'
  resources :inscriptions
  resources :etabs_filieres
  
  get 'bot_twitter/direct_message', to: 'bot_twitter#direct_message', as: 'new_msg_twitter'
  get 'bot_twitter/get_followers', to: 'bot_twitter#get_followers', as: 'list_followers'
  get 'bot_twitter/get_screen_name', to: 'bot_twitter#get_screen_name', as: 'list_screen_name'
  get 'bot_twitter/send_public_tweet', to: 'bot_twitter#send_public_tweet', as: 'send_public_tweet'
  get 'bot_twitter/send_private_tweet', to: 'bot_twitter#send_private_tweet', as: 'send_private_tweet'
  
  resources :newsletter

  resources :mailing
  
  resources :articles

  resources :provinces

  resources :etabs

  resources :filieres

  devise_for :users

  resources :vagues

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :etab
end

app/models/etab.rb
class Etab < ApplicationRecord
	mount_uploader :image, ImageUploader

	#un etab appartient à un user
	belongs_to :user
	#un etab a 0 ou plusieurs filieres
  has_many :etabs_filieres    
	has_many :filieres, through: :etabs_filieres
	
	has_many :articles
	has_many :vagues

	has_many :inscriptions    
	#has_many :user, through: :inscriptions 

	belongs_to :province

	def self.search(term)
		if term
		  where('lower(nom_etab) LIKE ?', "%#{term.downcase}%").order('id DESC')
		else
		  order('id DESC') 
		end
	end
	  
end

app/models/etabs_filiere.rb
class EtabsFiliere < ApplicationRecord
    belongs_to :filiere
    belongs_to :etab
    belongs_to :niveau
end

app/models/filiere.rb
class Filiere < ApplicationRecord

    #association model    
    has_many :etabs_filieres    
    has_many :etabs, through: :etabs_filieres
    has_many :niveaus, through: :etabs_filieres

    has_many :inscriptions
    
end

app/models/inscription.rb
class Inscription < ApplicationRecord
    belongs_to :etab
    belongs_to :user
    belongs_to :vague
    belongs_to :filiere
    belongs_to :niveau
    belongs_to :province
end

app/models/mailing.rb
class Mailing < ApplicationRecord
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
    validates :lastname, presence: true
    validates :firstname, presence: true
    validates :email, presence: true
end

app/models/niveau.rb
class Niveau < ApplicationRecord

    #association model
    has_many :etabs_filieres
    has_many :filieres, through: :etabs_filieres
    has_many :inscriptions
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :etabs
    has_many :inscriptions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  
  has_one :etab 
  mount_uploader :image, ImageUploader
 
  has_many :inscriptions    
	#has_many :etab, through: :inscriptions
end

app/models/vague.rb
class Vague < ApplicationRecord
    belongs_to :etab
    has_many :inscriptions
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_id, only: [:show, :update, :edit, :destroy]

  def index
    @articles = Article.page(params[:page]).per(5)
  end

  def new
    if user_signed_in?
      if current_user.role == "responsable"
        if current_user.etab != nil
          @article = Article.new
        else
          flash[:error] = "Créez dabord votre établissement !"
          redirect_to new_etab_path
        end
      else
        flash[:error] = "Vous n'êtes pas responsable !"
        redirect_to root_path
      end
    else
      flash[:error] = "Connectez dabord !"
      redirect_to new_user_session_path
    end
  end

  def create
    @article = Article.new(article_params)
    @article.etab = current_user.etab
    @article.save
    if @article
      flash[:success] = "Article enregistré avec succès"
      redirect_to articles_path
    else
      flash[:notice] = "Il y a peut-être un erreur"
      render "new"
    end
  end

  def edit
  end

  def update
    @article.update(article_params)
    if @article
      flash[:success] = "Modifié avec succès"
      redirect_to articles_path
    else
      flash[:notice] = "Il y a peut-être un erreur"
      render "edit"
    end
  end

  def show
  end

  def destroy
  end

  private

  def article_params
    params.require(:article).permit(:titre, :description, :image)
  end

  def get_id
    @article = Article.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@etab = Etab.order(created_at: :desc).page(1).per(8)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/bot_twitter_helper.rb
module BotTwitterHelper
end

app/helpers/filieres_helper.rb
module FilieresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailing_helper.rb
module MailingHelper
end

app/helpers/newsletter_helper.rb
module NewsletterHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/vagues_helper.rb
module VaguesHelper
end

app/views/articles/edit.html.erb
<section class="container-fluid padding-top-3x">
<!-- .row -->
<div class="row padding-top">
    <div class="container">
        <%= form_for @article, class:"form-horizontale" do |f| %>
        
            <div class="form-group">
                <label for="image">Photo représentant l'article</label>
                <div class="input-file-container">
                <%= f.file_field :image, autofocus: true, class: "input-file" %>
                <label tabindex="0" for="image" class="input-file-trigger">Importer une photo...</label>
                </div>
                <p class="file-return"></p>
            </div>
        
            <div class="form-group">
                <label for="titre">Titre de l'article</label>
                <%= f.text_field :titre, class: "form-control form-control-lg" %>
            </div>

            <div class="form-group">
                <label for="description">Description de l'article</label>
                <%= f.text_area :description, class: "form-control form-control-lg text-editor" %>
            </div>
        
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-primary">Créer mon article</button>
            </div>
        
        <% end %>
    </div>
</div>
</section>

<!-- Script js pour l'upload file -->
<script>
document.querySelector("html").classList.add('js');

var fileInput  = document.querySelector( ".input-file" ),  
 button     = document.querySelector( ".input-file-trigger" ),
 the_return = document.querySelector(".file-return");
   
button.addEventListener( "keydown", function( event ) {  
 if ( event.keyCode == 13 || event.keyCode == 32 ) {  
     fileInput.focus();  
 }  
});
button.addEventListener( "click", function( event ) {
fileInput.focus();
return false;
});  
fileInput.addEventListener( "change", function( event ) {  
 the_return.innerHTML = this.value;  
});  
</script>

app/views/articles/index.html.erb
    <!-- Single Post Content -->
    <section class="single-post-wrap">
      <!-- Close Btn -->
      <span class="close-btn"><i class="material-icons close"></i></span>
      <!-- Preloader -->
      <div class="preloader">
        <img src="img/preloader.gif" alt="Preloader">
      </div>
      <div class="inner">
        <div class="post-content">
          <!-- Content loaded via Ajax goes here -->
        </div><!-- .post-content -->
        <div class="post-share">
          <span>Share this post:&nbsp;&nbsp;&nbsp;</span>
          <div class="social-bar">
            <a href="blog.html#" class="sb-facebook" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
              <i class="socicon-facebook"></i>
            </a>
            <a href="blog.html#" class="sb-twitter" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
              <i class="socicon-twitter"></i>
            </a>
            <a href="blog.html#" class="sb-instagram" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
              <i class="socicon-instagram"></i>
            </a>
          </div>
        </div><!-- .post-share -->
      </div><!-- .inner -->
    </section><!-- .single-post-wrap -->

    <!-- Single Post Backdrop -->
    <div class="single-post-backdrop"></div>

    <!-- Content -->
    <section class="container padding-top-3x padding-bottom">
 

      





<% @articles.each do |article| %>

      <!-- Post -->
      <div class="row padding-top paddin-bottom">
        <div class="col-md-3 col-sm-4">
          <div class="blog-post-meta">
              <span>Par </span>
              <%= article.etab.nom_etab %>
              <span class="divider"></span>
              <%= article.created_at %>
            <!--div class="column">
              <a href="blog.html#">
                <i class="material-icons favorite_border"></i>
                7
              </a>
            </div-->
          </div>
          <h2 class="blog-post-title"><a href="<%= article_path(article.id) %>" class="ajax-post-link"><%= article.titre %></a></h2>
        </div>
        <div class="col-md-offset-1 col-sm-8">
          <%= image_tag article.image.url, :class => "space-bottom", :alt => "Blog Post" %>
          <p><%= article.description %></p>
          <div class="blog-post-meta space-top">
            <div class="column">
              <span>publié le </span>
              <%= article.created_at %>
            </div>
            <div class="column">
              <a href="<%= article_path(article.id) %>" class="read-more">Read More</a>
            </div>
          </div>
        </div>
      </div><!-- .row -->
      <hr>
    <% end %>  

      <!-- Pagination -->
      <div class="pagination">
        <%= paginate @articles %>
    </section><!-- .container -->

app/views/articles/new.html.erb
 <section class="container-fluid padding-top-3x">
    <!-- .row -->
    <div class="row padding-top">
        <div class="container">
            <%= form_for @article, class:"form-horizontale" do |f| %>
            
                <div class="form-group">
                    <label for="image">Photo représentant l'article</label>
                    <div class="input-file-container">
                    <%= f.file_field :image, autofocus: true, class: "input-file" %>
                    <label tabindex="0" for="image" class="input-file-trigger">Importer une photo...</label>
                    </div>
                    <p class="file-return"></p>
                </div>
            
                <div class="form-group">
                    <label for="titre">Titre de l'article</label>
                    <%= f.text_field :titre, class: "form-control form-control-lg" %>
                </div>

                <div class="form-group">
                    <label for="description">Description de l'article</label>
                    <%= f.text_area :description, class: "form-control form-control-lg text-editor" %>
                </div>
            
                <div class="form-group">
                    <button type="submit" class="btn btn-lg btn-primary">Créer mon article</button>
                </div>
            
            <% end %>
        </div>
    </div>
</section>
 
  <!-- Script js pour l'upload file -->
  <script>
 document.querySelector("html").classList.add('js');
 
 var fileInput  = document.querySelector( ".input-file" ),  
     button     = document.querySelector( ".input-file-trigger" ),
     the_return = document.querySelector(".file-return");
       
 button.addEventListener( "keydown", function( event ) {  
     if ( event.keyCode == 13 || event.keyCode == 32 ) {  
         fileInput.focus();  
     }  
 });
 button.addEventListener( "click", function( event ) {
    fileInput.focus();
    return false;
 });  
 fileInput.addEventListener( "change", function( event ) {  
     the_return.innerHTML = this.value;  
 });  
 </script>

app/views/articles/show.html.erb
<section class="col-md-offset-3 padding-top-3x padding-left-right">
    <h1 class="mobile-center"><span class="text-semibold"><%= @article.titre %></span></h1>
    <div class="row padding-top">
       <div class="col-sm-8 padding-bottom-2x">
          <!-- Nav Tabs -->
 
			<div class="show-etab-img" style="background-image:url(<%= @article.image.url %>)">
			</div><br>
			<%= @article.description %>
			<hr>
                      <h3 class="subheadline">Commentaires</h3>
                        <div id="disqus_thread"></div>
                        <script>
                        /**
                        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
                        /*
                        var disqus_config = function () {
                        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                        };
                        */
                        (function() { // DON'T EDIT BELOW THIS LINE
                        var d = document, s = d.createElement('script');
                        s.src = 'https://e-anatra-1.disqus.com/embed.js';
                        s.setAttribute('data-timestamp', +new Date());
                        (d.head || d.body).appendChild(s);
                        })();
                        </script>
                        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

          <!-- .tab-content -->
       </div>
       <!-- .col-sm-8 -->
    </div>
    <!-- .row -->
 </section>