config/routes.rb
Rails.application.routes.draw do

  get 'status_etudiants/index/:id', to: "status_etudiants#index", as: 'satusE'
  resources :inscriptions
  resources :etabs_filieres
  
  get 'bot_twitter/direct_message', to: 'bot_twitter#direct_message', as: 'new_msg_twitter'
  get 'bot_twitter/get_followers', to: 'bot_twitter#get_followers', as: 'list_followers'
  get 'bot_twitter/get_screen_name', to: 'bot_twitter#get_screen_name', as: 'list_screen_name'
  get 'bot_twitter/send_public_tweet', to: 'bot_twitter#send_public_tweet', as: 'send_public_tweet'
  get 'bot_twitter/send_private_tweet', to: 'bot_twitter#send_private_tweet', as: 'send_private_tweet'
  
  resources :newsletter

  resources :mailing
  
  resources :articles

  resources :provinces

  resources :etabs

  resources :filieres

  devise_for :users

  resources :vagues

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :etab
end

app/models/etab.rb
class Etab < ApplicationRecord
	mount_uploader :image, ImageUploader

	#un etab appartient à un user
	belongs_to :user
	#un etab a 0 ou plusieurs filieres
  has_many :etabs_filieres    
	has_many :filieres, through: :etabs_filieres
	
	has_many :articles
	has_many :vagues

	has_many :inscriptions    
	#has_many :user, through: :inscriptions 

	belongs_to :province

	def self.search(term)
		if term
		  where('lower(nom_etab) LIKE ?', "%#{term.downcase}%").order('id DESC')
		else
		  order('id DESC') 
		end
	end
	  
end

app/models/etabs_filiere.rb
class EtabsFiliere < ApplicationRecord
    belongs_to :filiere
    belongs_to :etab
    belongs_to :niveau
end

app/models/filiere.rb
class Filiere < ApplicationRecord

    #association model    
    has_many :etabs_filieres    
    has_many :etabs, through: :etabs_filieres
    has_many :niveaus, through: :etabs_filieres

    has_many :inscriptions
    
end

app/models/inscription.rb
class Inscription < ApplicationRecord
    belongs_to :etab
    belongs_to :user
    belongs_to :vague
    belongs_to :filiere
    belongs_to :niveau
    belongs_to :province
end

app/models/mailing.rb
class Mailing < ApplicationRecord
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
    validates :lastname, presence: true
    validates :firstname, presence: true
    validates :email, presence: true
end

app/models/niveau.rb
class Niveau < ApplicationRecord

    #association model
    has_many :etabs_filieres
    has_many :filieres, through: :etabs_filieres
    has_many :inscriptions
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :etabs
    has_many :inscriptions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  
  has_one :etab 
  mount_uploader :image, ImageUploader
 
  has_many :inscriptions    
	#has_many :etab, through: :inscriptions
end

app/models/vague.rb
class Vague < ApplicationRecord
    belongs_to :etab
    has_many :inscriptions
end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController
  def index
  end

  def show
    if user_signed_in?
      if current_user.role == "responsable"
        if current_user.etab != nil
          @inscriptions = Inscription.where(etab_id: params[:id])
        end
      end
    end
  end

  def new
    if user_signed_in?
      if current_user.role == "etudiant" 
        #si c'est un étudiant
        @inscription = Inscription.new
      else
        flash[:error] = "Vous n'êtes pas un étudiant!"
        redirect_to etabs_path
      end
    else
      flash[:error] = "Connecter vous d'abord!"
      redirect_to user_session_path
    end
  end

  def create
    @etab = Etab.find(params[:inscription][:etab_id])
    @filiere = Filiere.find(params[:inscription][:filiere_id])
    @province = Province.find(params[:inscription][:province_id])
    @vague = Vague.find(params[:inscription][:vague_id])
    @niveau = Niveau.find(params[:inscription][:niveau_id])

  
      #tout les inscrits dans une établissement donné
        @inscrit = Inscription.where(etab_id: @etab.id)
        couple =false
        @inscrit.each do |assoc|
          #if ((assoc.user == current_user) && (assoc.vague == @vague) && (assoc.etab == @etab) && (assoc.province == @province) && (assoc.filiere == @filiere) && (assoc.niveau == @niveau))
          if ((assoc.user == current_user) && (assoc.etab == @etab))   
          # couple déjà existé
                couple = true
          end
        end

        # couple déjà existé
        if couple
            flash[:error] = "Vous êtes déjà inscrit!"
            redirect_to satusE_path(current_user.id)
        else
            inscri = Inscription.new()
            inscri.filiere = @filiere
            inscri.etab = @etab
            inscri.niveau = @niveau
            inscri.vague = @vague
            inscri.province = @province
            inscri.user = current_user
            
            if inscri.save
                flash[:success]= "Félicitation, vous êtes inscrit, un email de confirmation vous a envoyé!"
                ContactMailer.new_subscription(@etab.user,current_user).deliver_now
                redirect_to satusE_path(current_user.id)
            else
                flash[:error] = "Erreur lors d'inscription! Champ invalid peut être"
                redirect_to new_inscription_path
            end
        end
  end

  def edit
    @etudiant = Inscription.find(params[:id])
    if @etudiant.valide == false
      @etudiant.valide = true
      if @etudiant.save
        flash[:success] = "Validation ok!"
        ContactMailer.inscrit(@etudiant.user,current_user).deliver_now
        redirect_to inscription_path(current_user.etab.id)
      else
        flash[:success] = "Erreur!"
        redirect_to inscription_path(current_user.etab.id)
      end
    else
      @etudiant.valide = false
      if @etudiant.save
        flash[:success] = "Annulation ok!"
        redirect_to inscription_path(current_user.etab.id)
      else
        flash[:success] = "Erreur!"
        redirect_to inscription_path(current_user.etab.id)
      end
    end
  end

  def update
    # #validation etudiant & envoyer mail à l'étudiant en question pour lui dire que son inscription est validé ou non
    # @etudiant = Inscription.find(params[:id])
    # @etudiant.valide = true
    # if @etudiant.save
    #   flash[:success] = "Validation ok!"
    #   redirect_to inscription_path(current_user.etab.id)
    # else
    #   flash[:success] = "Erreur!"
    #   redirect_to inscription_path(current_user.etab.id)
    # end
  end

  def destroy
    @etudiant = Inscription.find(params[:id])
    @etudiant.destroy
    redirect_to inscription_path(current_user.etab.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/bot_twitter_helper.rb
module BotTwitterHelper
end

app/helpers/filieres_helper.rb
module FilieresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inscriptions_helper.rb
module InscriptionsHelper
end

app/helpers/mailing_helper.rb
module MailingHelper
end

app/helpers/newsletter_helper.rb
module NewsletterHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/vagues_helper.rb
module VaguesHelper
end

app/views/inscriptions/create.html.erb
<%= form_for @inscription  do |f| %>

    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col col-md-12 col-lg-10 col-xl-8">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Etudiants</a></li>
              <li class="breadcrumb-item active" aria-current="page">Inscription</li>
            </ol>
          </nav>
          <div class="page-header">
            <h1>S'inscrire à un établissement</h1>
          </div>
        </div>
      </div>
    </div>
    <div id="content">
      <div class="container">
        <div class="row justify-content-md-center align-items-center">
          <div class="col col-md-12 col-lg-10 col-xl-8">
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="login">
                <form>
                   <div class="row login-row">
                      <div class="col">
                        Province de votre établissement
                         <%= f.collection_select :province_id, Province.order(:province_name), :id, :province_name, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                      </div>
    
                      <div class="col">
                        Votre établissement
                         <%= f.collection_select :etablissement_id, Etablissement.order(:nom), :id, :nom, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                      </div>
                   </div>
                   <div class="row login-row">
    
                      <div class="col">
                        Filière
                         <%= f.collection_select :filiere_id, Filiere.order(:nom), :id, :nom, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                      </div>
    
                      <div class="col">
                        Rentrée
                         <%= f.collection_select :vague_id, Vague.order(:rentree), :id, :rentree, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                      </div>
                   </div>
    
                   <div class="row login-row">
                      <div class="col">
                        Niveau d'étude
                         <%= f.collection_select :level_id, Level.order(:niveau), :id, :niveau, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                      </div>
                   </div>
                   
                   <div class="row">
                      <div class="col">
                         <button type="submit" class="btn btn-primary btn-lg">S'inscrire</button>
                      </div>
                      <div class="col">
                      </div>
                   </div>
                </form>
              </div>
            </div>
            <div> </div>
          </div>
        </div>
      </div>
    </div>
    
    
    
    <% end %>

app/views/inscriptions/delete.html.erb
<h1>Inscriptions#delete</h1>
<p>Find me in app/views/inscriptions/delete.html.erb</p>

app/views/inscriptions/edit.html.erb
<h1>Edit inscription </h1>

app/views/inscriptions/index.html.erb
<h1>Inscriptions#index</h1>
<p>Find me in app/views/inscriptions/index.html.erb</p>

app/views/inscriptions/new.html.erb
<%= form_for @inscription  do |f| %>

<section class="col-md-offset-3 padding-left-right padding-top-3x">
    <h1 class="mobile-center">S'inscrire à un <span class="text-semibold">établissement</span></h1>
    <div class="row padding-top">
       <div class="col-sm-8">
          <!-- Nav Tabs -->
          
          <!-- .nav-tabs -->
          <!-- Tab Panes -->
          <div class="tab-content">
             <div role="tabpanel" class="tab-pane transition fade scale in active" id="profile">
                <form method="post">

                   <div class="form-element">
                      <label for="niveau">Ou se situe votre établissement</label>
                      <%= f.collection_select :province_id, Province.order(:province_name), :id, :province_name, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                   </div>

                   <div class="form-element">
                      <label for="niveau">Nom de votre établissement</label>
                      <%= f.grouped_collection_select :etab_id, Province.order(:province_name), :etabs, :province_name, :id, :nom_etab, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                   </div>

                   <div class="form-element">
                      <label for="niveau">Date de la rentrée</label>
                      <%= f.grouped_collection_select :vague_id, Etab.order(:nom_etab), :vagues, :nom_etab, :id, :debut_session, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                   </div>

                   <div class="form-element">
                      <label for="niveau">Filière</label>
                      <%= f.grouped_collection_select :filiere_id, Etab.order(:nom_etab), :filieres, :nom_etab, :id, :filiere, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                   </div>

                   <div class="form-element">
                      <label for="niveau">Niveau d'étude</label>
                      <%= f.grouped_collection_select :niveau_id, Filiere.order(:filiere), :niveaus, :filiere, :id, :niveau, {:include_blank => true}, {class: "form-control form-control-lg"}  %>
                   </div>

                   <div class="row">
                      <div class="col-sm-6">
                         
                      </div>
                      <div class="col-sm-6 text-right mobile-center"><br>
                         <button type="submit" class="btn btn-primary waves-effect waves-light">S'inscrire</button>
                      </div>
                   </div>

                </form>
             </div>
          </div>
          <!-- .tab-content -->
       </div>
       <!-- .col-sm-8 -->
    </div>
    <!-- .row -->
 </section>

<% end %>
<div class="marge-30px"></div>

app/views/inscriptions/show.html.erb
<section class="container padding-top-3x">
  <h1 class="space-top-half tablet-center">Tout les élèves inscrit dans mon établissement</h1>
</section><!-- .container-fluid -->

<section class="container padding-bottom-3x">
    <div class="row">
        <div class="table-responsive">
        <table class="table">
            <thead>
                <th>Nom etudiant</th><th>Prenom etudiant</th><th>Filiere</th><th>Niveau</th><th>Debut Session</th><th>Fin Session</th><th></th><th></th>
            </thead>
            <tbody>
            <% @inscriptions.each do |f| %>
                <tr>
                    <td><%= f.user.name %></td>
                    <td><%= f.user.first_name %></td>
                    <td><%= f.filiere.filiere %></td>
                    <td><%= f.niveau.niveau %></td>
                    <td><%= Date.parse(f.vague.debut_session.to_s).strftime('%a %d %b %Y') %> </td>
                    <td><%= Date.parse(f.vague.fin_session.to_s).strftime('%a %d %b %Y') %> </td>
                    <td>
                        <% if f.valide == false %>
                            <a href="<%= edit_inscription_path(f.id) %>" class="btn btn-primary" >Valider</a>
                        <% else %>
                            <span>Inscrit/</span><span><a href="<%= edit_inscription_path(f.id) %>" >Annuler</a></span>
                        <% end %>
                    </td>
                    <td>
                        <a href="<%= inscription_path(f.id) %>" class="btn btn-danger" data-confirm="Êtes vous sur ?" data-method="DELETE">Supprimer</a>
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
        </table>
    </div>
</section>

app/views/inscriptions/update.html.erb
<h1>Inscriptions#update</h1>
<p>Find me in app/views/inscriptions/update.html.erb</p>