config/routes.rb
Rails.application.routes.draw do

  get 'status_etudiants/index/:id', to: "status_etudiants#index", as: 'satusE'
  resources :inscriptions
  resources :etabs_filieres
  
  get 'bot_twitter/direct_message', to: 'bot_twitter#direct_message', as: 'new_msg_twitter'
  get 'bot_twitter/get_followers', to: 'bot_twitter#get_followers', as: 'list_followers'
  get 'bot_twitter/get_screen_name', to: 'bot_twitter#get_screen_name', as: 'list_screen_name'
  get 'bot_twitter/send_public_tweet', to: 'bot_twitter#send_public_tweet', as: 'send_public_tweet'
  get 'bot_twitter/send_private_tweet', to: 'bot_twitter#send_private_tweet', as: 'send_private_tweet'
  
  resources :newsletter

  resources :mailing
  
  resources :articles

  resources :provinces

  resources :etabs

  resources :filieres

  devise_for :users

  resources :vagues

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :etab
end

app/models/etab.rb
class Etab < ApplicationRecord
	mount_uploader :image, ImageUploader

	#un etab appartient à un user
	belongs_to :user
	#un etab a 0 ou plusieurs filieres
  has_many :etabs_filieres    
	has_many :filieres, through: :etabs_filieres
	
	has_many :articles
	has_many :vagues

	has_many :inscriptions    
	#has_many :user, through: :inscriptions 

	belongs_to :province

	def self.search(term)
		if term
		  where('lower(nom_etab) LIKE ?', "%#{term.downcase}%").order('id DESC')
		else
		  order('id DESC') 
		end
	end
	  
end

app/models/etabs_filiere.rb
class EtabsFiliere < ApplicationRecord
    belongs_to :filiere
    belongs_to :etab
    belongs_to :niveau
end

app/models/filiere.rb
class Filiere < ApplicationRecord

    #association model    
    has_many :etabs_filieres    
    has_many :etabs, through: :etabs_filieres
    has_many :niveaus, through: :etabs_filieres

    has_many :inscriptions
    
end

app/models/inscription.rb
class Inscription < ApplicationRecord
    belongs_to :etab
    belongs_to :user
    belongs_to :vague
    belongs_to :filiere
    belongs_to :niveau
    belongs_to :province
end

app/models/mailing.rb
class Mailing < ApplicationRecord
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
    validates :lastname, presence: true
    validates :firstname, presence: true
    validates :email, presence: true
end

app/models/niveau.rb
class Niveau < ApplicationRecord

    #association model
    has_many :etabs_filieres
    has_many :filieres, through: :etabs_filieres
    has_many :inscriptions
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :etabs
    has_many :inscriptions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  
  has_one :etab 
  mount_uploader :image, ImageUploader
 
  has_many :inscriptions    
	#has_many :etab, through: :inscriptions
end

app/models/vague.rb
class Vague < ApplicationRecord
    belongs_to :etab
    has_many :inscriptions
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/filieres_helper.rb
module FilieresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailing_helper.rb
module MailingHelper
end

app/helpers/newsletter_helper.rb
module NewsletterHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/vagues_helper.rb
module VaguesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-anatra 2.0</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" href="/favicon.png" />
    <!--SEO Meta Tags-->
    <meta name="description" content="M-Store - Modern E-Commerce Template" />
    <meta name="keywords" content="shop, e-commerce, modern, minimalist style, responsive, online store, business, mobile, blog, bootstrap, html5, css3, jquery, js, gallery, slider, touch, creative, clean" />
    <meta name="author" content="Rokaux" />

    <!--Mobile Specific Meta Tag-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <link href="https://fonts.googleapis.com/css?family=Paytone+One" rel="stylesheet">
    <!--Favicon-->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <!-- Google Material Icons -->
    <link href="/css/vendor/material-icons.min.css" rel="stylesheet" media="screen">

    <!-- Brand Icons -->
    <link href="/css/vendor/socicon.min.css" rel="stylesheet" media="screen">

    <!-- Bootstrap -->
    <link href="/css/vendor/bootstrap.min.css" rel="stylesheet" media="screen">

    <!-- Theme Styles -->
    <link href="/css/theme.min.css" rel="stylesheet" media="screen">

    <link rel="stylesheet" href="/imput_file/css/style.css">
    
    <!-- Google map -->
    <link rel="stylesheet" href="/css/maps.css">
    
    <!-- Page Preloading -->
    
    <script src="/js/vendor/page-preloading.js"></script>

    <!-- Modernizr -->
    <script src="/js/vendor/modernizr.custom.js"></script>

  </head>

  <body class="page-preloading">

    <!-- Page Pre-Loader -->
    <div class="page-preloader">
      <div class="preloader">
        <img src="/img/preloader.gif" alt="Preloader">
      </div>
    </div><!-- .page-preloader -->
    <!-- Navbar -->
    <!-- Remove ".navbar-sticky" class to make navigation bar scrollable with the page. -->
    <header class="navbar navbar-sticky">
         <!-- Site Logo -->
         <a href="/" class="site-logo visible-desktop">
         <span>[</span> E
         <span class="text-gray">/</span>
         ANATRA <span>]</span>
         </a><!-- site-logo.visible-desktop -->
         <a href="index.html" class="site-logo visible-mobile">
         <span>[</span> E <span>]</span>
         </a>

         <nav class="main-navigation text-center">
            <ul class="menu">
               <li class="current-menu-item">
                  <a href="/">Accueil</a>
               </li>
               <li>
                  <a href="<%= etabs_path %>">Trouver son école</a>
               </li>

               <li class="menu-item-has-children">
                  
                  <% if user_signed_in? %>
                        <!-- RESPONSABLE --> 
                        <% if current_user.role == "responsable" %>  
                          <a href="#">Responsable</a>
                          <ul class="sub-menu">
                            <li class="submenu-item-has-children">
                              <a href="<%= etabs_path %>">ETABLISSEMENT</a>
                              <ul class="sub-menu">
                                <li><a href="<%= etabs_path %>">Tout les établissements</a></li>
                                <% if current_user.etab != nil %>
                                  <li><a href="<%= etab_path(current_user.etab.id) %>">Mon etablissement</a></li>
                                  <li><a href="<%= edit_etab_path(current_user.etab.id) %>">Modifier</a></li>
                                  <li><a href="<%= new_article_path %>">Créer article</a></li>
                                  <li><a href="<%= new_vague_path %>">Créer une session</a></li>
                                  <li><a href="<%= inscription_path(current_user.etab.id) %>">Tout les étudiants inscrits</a></li>
                                <% else %>
                                  <li><a href="<%= new_etab_path %>">Créez votre établissement</a></li>
                                <% end %>
                              </ul>
                            </li>
                            <li class="submenu-item-has-children">
                              <a href="<%= filieres_path %>">FILIERE</a>
                              <ul class="sub-menu">
                                <li><a href="<%= filieres_path %>">Toutes les filières</a></li>
                                <% if current_user.etab != nil %>
                                  <li><a href="<%= etabs_filiere_path(current_user.etab.id) %>">Mes filières</a></li>
                                  <li><a href="<%= new_etabs_filiere_path %>">Ajouter</a></li>
                                <% end %>
                              </ul>
                            </li>
                            
                          </ul>
                          <!-- ETUDIANT -->
                        <% else %>
                          <a href="#">Etudiant</a>
                          <ul class="sub-menu">
                            <li class="submenu-item-has-children">
                              <a href="<%= etabs_path %>">ETABLISSEMENT</a>
                              <ul class="sub-menu">
                                <li><a href="<%= etabs_path %>">Tout les établissements</a></li>
                              </ul>
                            </li>
                            
                            <li class="submenu-item-has-children">
                              <a href="#">INSCRIPTION</a>
                              <ul class="sub-menu">
                                <li><a href="<%= new_inscription_path %>">S'inscrire</a></li>
                                <li><a href="<%= satusE_path(current_user.id) %>">Votre status</a></li>
                              </ul>
                            </li>
                          </ul>
                        <% end %>
                        <% else %>
                        <a href="#">Visiteur</a>
                        <ul class="sub-menu">
                          <li class="submenu-item-has-children">
                            <a href="#">ETABLISSEMENTS</a>
                            <ul class="sub-menu">
                              <li><a href="#">Tout les établissements</a></li>
                            </ul>
                          </li>
                          <li class="submenu-item-has-children">
                            <a href="#">FILIERES</a>
                            <ul class="sub-menu">
                              <li><a href="#">Toutes les filières</a></li>
                            </ul>
                          </li>
                          <li><a href="#">ORIENTATION</a></li>
                            <a href="<%= etabs_path %>">ETABLISSEMENT</a>
                            <ul class="sub-menu">
                              <li><a href="<%= etabs_path %>">Tout les établissements</a></li>
                            </ul>
                          </li>
                          
                        </ul>
                    <%  end %>
                    <!-- VISITEUR -->
                
              </li>


               <li>
                  <a href="<%= articles_path %>">Blog</a>
               </li>
               <!--li class="menu-item-has-children">
                  <a href="#">Pages</a>
                  <ul class="sub-menu">
                     <li><a href="about.html">About</a></li>
                     <li><a href="contacts.html">Contacts</a></li>
                     <li><a href="faq.html">FAQ</a></li>
                  </ul>
               </li-->
            </ul>
            <!-- .menu -->
         </nav>

         <!-- .main-navigation -->
         <!-- Toolbar -->
          <div class="toolbar">
            <div class="inner">
              <a href="#" class="mobile-menu-toggle"><i class="material-icons menu"></i></a>

              <% if user_signed_in? %>
                <!--a href="#"><i class="material-icons check_circle"></i></a-->
                <a href="/users/edit">
                  <%= image_tag(current_user.image.thumb.url, class: "user-profile") %>
                </a>
                <div class="cart-btn">
                  <%= link_to "", destroy_user_session_path, method: :delete, class: "material-icons remove_circle" %>
                </div>
                <!--a data-method="delete" href="<%= destroy_user_session_path %>" >
                    <i>
                      <span class="material-icons remove_circle"></span>
                    </i>
                </a-->

              <% else %>
                <a href="/users/sign_in"><i class="material-icons person"></i></a>
                <div class="cart-btn">
                  <a href="/users/sign_up">
                    <i>
                      <span class="material-icons person_add"></span>
                    </i>
                  </a>
                </div><!-- .cart-btn -->
              <% end %>

            </div><!-- .inner -->
          </div>
         <!-- .toolbar -->
    </header>
    <!-- .navbar.navbar-sticky -->

    <!-- LOGIN MESSAGE -->
    <% flash.each do |name, msg| %>
    <div class="row margin-top" id="xxx">
      <section class="col-md-offset-3 padding-left-right margin-for-alert">
        <div class="alert-contain navbar-message">
          <div class="alert-new alert-<%= name %> alert-dismissible show"  role="alert">
              <%= msg %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"  id="x">
                <span aria-hidden="true">&times;</span>
              </button>
          </div>
        </div>
      </section>
    </div>
    <% end %>


    <%= yield %>

    <!-- Footer -->
    <footer class="footer">
       <div class="column">
          <p class="text-sm">Pour plus d'information ? <span class="text-primary">(+261) 34 92 785 51</span></p>
          <div class="social-bar text-center space-bottom">
             <a href="#" class="sb-skype" data-toggle="tooltip" data-placement="top" title="Skype">
             <i class="socicon-skype"></i>
             </a>
             <a href="https://www.facebook.com/E-anatra-178591866120655" class="sb-facebook" data-toggle="tooltip" data-placement="top" title="Facebook">
             <i class="socicon-facebook"></i>
             </a>
             <a href="#" class="sb-google-plus" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google+">
             <i class="socicon-googleplus"></i>
             </a>
             <a href="#" class="sb-twitter" data-toggle="tooltip" data-placement="top" title="Twitter">
             <i class="socicon-twitter"></i>
             </a>
             <a href="#" class="sb-instagram" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
             <i class="socicon-instagram"></i>
             </a>
          </div>
          <!-- .social-bar -->
          <p class="copyright">&copy; 2018. Made with <i class="text-danger material-icons favorite"></i> with ruby on rails</p>
       </div>
       <!-- .column -->
       <div class="column">
          <h3 class="widget-title">
             Inscrivez-vous
             <small>Pour recevoir nos actualités.</small>
          </h3>
            <%= form_tag newsletter_index_path, method: "post", class: "subscribe-form" %>
             <a type="button" class="form-control btn btn-primary" href="<%= new_newsletter_path %>"><i class="material-icons email"></i> Newsletter </a>
             <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
             <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c7103e2c981361a6639545bd5_1194bb7544" tabindex="-1" value=""></div>
       </div>
       <!-- .column -->
       <div class="column">
          <h3 class="widget-title">
             Mode de payement
             <small>mobile money</small>
          </h3>
          <div class="cards"><img class="mvola" src="/img/cards.png" alt="Cards"></div>
          <!-- Scroll To Top Button -->
          <div class="scroll-to-top-btn"><i class="material-icons trending_flat"></i></div>
       </div>
       <!-- .column -->
    </footer>
    <!-- .footer -->
    </div><!-- .page-wrapper -->
    <!-- JavaScript (jQuery) libraries, plugins and custom scripts -->
    <script src="/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="/js/vendor/bootstrap.min.js"></script>
    <script src="/js/vendor/smoothscroll.js"></script>
    <script src="/js/vendor/velocity.min.js"></script>
    <script src="/js/vendor/waves.min.js"></script>
    <script src="/js/vendor/icheck.min.js"></script>
    <script src="/js/vendor/owl.carousel.min.js"></script>
    <script src="/js/vendor/jquery.downCount.js"></script>
    <script src="/js/vendor/magnific-popup.min.js"></script>
    <script src="/js/scripts.js"></script>
    <!--script src="/imput_file/js/index.js"></script-->
    
    <!-- JS pour google map -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyC67N2lv2tfsygV77l2PXdD7l2hkMQEBpc"></script>
  </body>
</html>